// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// getWindow
NumericVector getWindow(int x, int size);
RcppExport SEXP _spatialTIME_getWindow(SEXP xSEXP, SEXP sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type size(sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(getWindow(x, size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_matrix_subsetting
NumericMatrix cpp_matrix_subsetting(NumericMatrix m, NumericVector rows, NumericVector cols);
RcppExport SEXP _spatialTIME_cpp_matrix_subsetting(SEXP mSEXP, SEXP rowsSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_matrix_subsetting(m, rows, cols));
    return rcpp_result_gen;
END_RCPP
}
// compute_perms
NumericVector compute_perms(SEXP perms1, double r_val, SEXP distances1, SEXP edge1, double area);
RcppExport SEXP _spatialTIME_compute_perms(SEXP perms1SEXP, SEXP r_valSEXP, SEXP distances1SEXP, SEXP edge1SEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< SEXP >::type perms1(perms1SEXP);
    Rcpp::traits::input_parameter< double >::type r_val(r_valSEXP);
    Rcpp::traits::input_parameter< SEXP >::type distances1(distances1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type edge1(edge1SEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_perms(perms1, r_val, distances1, edge1, area));
    return rcpp_result_gen;
END_RCPP
}
// compute_perms3
NumericVector compute_perms3(SEXP perms1, double r_val, SEXP distances1, SEXP edge1, double area);
RcppExport SEXP _spatialTIME_compute_perms3(SEXP perms1SEXP, SEXP r_valSEXP, SEXP distances1SEXP, SEXP edge1SEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type perms1(perms1SEXP);
    Rcpp::traits::input_parameter< double >::type r_val(r_valSEXP);
    Rcpp::traits::input_parameter< SEXP >::type distances1(distances1SEXP);
    Rcpp::traits::input_parameter< SEXP >::type edge1(edge1SEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_perms3(perms1, r_val, distances1, edge1, area));
    return rcpp_result_gen;
END_RCPP
}
// compute_perms2
NumericVector compute_perms2(NumericMatrix perms, NumericVector r_range, NumericMatrix distances, NumericMatrix edge, double area);
RcppExport SEXP _spatialTIME_compute_perms2(SEXP permsSEXP, SEXP r_rangeSEXP, SEXP distancesSEXP, SEXP edgeSEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type perms(permsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r_range(r_rangeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_perms2(perms, r_range, distances, edge, area));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spatialTIME_getWindow", (DL_FUNC) &_spatialTIME_getWindow, 2},
    {"_spatialTIME_cpp_matrix_subsetting", (DL_FUNC) &_spatialTIME_cpp_matrix_subsetting, 3},
    {"_spatialTIME_compute_perms", (DL_FUNC) &_spatialTIME_compute_perms, 5},
    {"_spatialTIME_compute_perms3", (DL_FUNC) &_spatialTIME_compute_perms3, 5},
    {"_spatialTIME_compute_perms2", (DL_FUNC) &_spatialTIME_compute_perms2, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_spatialTIME(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
