// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_matrix_subsetting
NumericMatrix cpp_matrix_subsetting(NumericMatrix m, NumericVector rows, NumericVector cols);
RcppExport SEXP _spatialTIME_cpp_matrix_subsetting(SEXP mSEXP, SEXP rowsSEXP, SEXP colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cols(colsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_matrix_subsetting(m, rows, cols));
    return rcpp_result_gen;
END_RCPP
}
// compute_perms
NumericVector compute_perms(NumericMatrix perms, double r_val, NumericMatrix distances, NumericMatrix edge, double area);
RcppExport SEXP _spatialTIME_compute_perms(SEXP permsSEXP, SEXP r_valSEXP, SEXP distancesSEXP, SEXP edgeSEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type perms(permsSEXP);
    Rcpp::traits::input_parameter< double >::type r_val(r_valSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_perms(perms, r_val, distances, edge, area));
    return rcpp_result_gen;
END_RCPP
}
// compute_perms2
NumericVector compute_perms2(NumericMatrix perms, NumericVector r_range, NumericMatrix distances, NumericMatrix edge, double area);
RcppExport SEXP _spatialTIME_compute_perms2(SEXP permsSEXP, SEXP r_rangeSEXP, SEXP distancesSEXP, SEXP edgeSEXP, SEXP areaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type perms(permsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r_range(r_rangeSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type distances(distancesSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type edge(edgeSEXP);
    Rcpp::traits::input_parameter< double >::type area(areaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_perms2(perms, r_range, distances, edge, area));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spatialTIME_cpp_matrix_subsetting", (DL_FUNC) &_spatialTIME_cpp_matrix_subsetting, 3},
    {"_spatialTIME_compute_perms", (DL_FUNC) &_spatialTIME_compute_perms, 5},
    {"_spatialTIME_compute_perms2", (DL_FUNC) &_spatialTIME_compute_perms2, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_spatialTIME(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
