# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getWindow <- function(x, size) {
    .Call('_spatialTIME_getWindow', PACKAGE = 'spatialTIME', x, size)
}

cpp_matrix_subsetting <- function(m, rows, cols) {
    .Call('_spatialTIME_cpp_matrix_subsetting', PACKAGE = 'spatialTIME', m, rows, cols)
}

#' Compute the permutations of permuations of a distance matrix
#' 
#' @param perm1 a numeric matrix containing rows in `distances1` and `edge1` to use as positive cell locations
#' @param r_val a single r value which to count within for Ripley's K
#' @param distances1,edge1 matrices containing equal columns and rows for distances between cells and edge correction corresponding to cell pairs
#' @param area a single value that contains the area of the window around points
#' 
#' @return a vector of K statistics of length nrow(perms1)
#' @export
#' 
#' @examples
#' perms1 = as.matrix(sample(1:10, 5, replace = F))
#' r_val = 1
#' distances1 = matrix(nrow = 10, data = abs(rnorm(100)))
#' edge1 = distances1 #no edge correction
#' area = 100
#' K = compute_perms(perms1, r_val, distances1, edge1, area)
compute_perms <- function(perms1, r_val, distances1, edge1, area) {
    .Call('_spatialTIME_compute_perms', PACKAGE = 'spatialTIME', perms1, r_val, distances1, edge1, area)
}

compute_perms3 <- function(perms1, r_val, distances1, edge1, area) {
    .Call('_spatialTIME_compute_perms3', PACKAGE = 'spatialTIME', perms1, r_val, distances1, edge1, area)
}

compute_perms2 <- function(perms, r_range, distances, edge, area) {
    .Call('_spatialTIME_compute_perms2', PACKAGE = 'spatialTIME', perms, r_range, distances, edge, area)
}

