# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_matrix_subsetting <- function(m, rows, cols) {
    .Call(`_spatialTIME_cpp_matrix_subsetting`, m, rows, cols)
}

compute_perms <- function(perms, r_val, distances, edge, area) {
    .Call(`_spatialTIME_compute_perms`, perms, r_val, distances, edge, area)
}

compute_perms2 <- function(perms, r_range, distances, edge, area) {
    .Call(`_spatialTIME_compute_perms2`, perms, r_range, distances, edge, area)
}

